# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\x04\x64\x65mo\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t2j\n\nCalculator\x12*\n\x03\x41\x64\x64\x12\x10.demo.AddRequest\x1a\x11.demo.AddResponse\x12\x30\n\x05Hello\x12\x12.demo.HelloRequest\x1a\x13.demo.HelloResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=26
  _globals['_ADDREQUEST']._serialized_end=60
  _globals['_ADDRESPONSE']._serialized_start=62
  _globals['_ADDRESPONSE']._serialized_end=91
  _globals['_HELLOREQUEST']._serialized_start=93
  _globals['_HELLOREQUEST']._serialized_end=121
  _globals['_HELLORESPONSE']._serialized_start=123
  _globals['_HELLORESPONSE']._serialized_end=156
  _globals['_CALCULATOR']._serialized_start=158
  _globals['_CALCULATOR']._serialized_end=264
# @@protoc_insertion_point(module_scope)
